CREATE TABLE `soulprint_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`assessmentId` int,
	`guestName` varchar(255),
	`guestEmail` varchar(320),
	`birthDate` varchar(16) NOT NULL,
	`birthTime` varchar(8),
	`birthCity` varchar(255) NOT NULL,
	`birthCountry` varchar(128),
	`birthLatitude` varchar(32),
	`birthLongitude` varchar(32),
	`tier` enum('blueprint','compass','oracle') NOT NULL DEFAULT 'compass',
	`reportType` enum('soulprint_only','combined') NOT NULL DEFAULT 'combined',
	`isAlpha` boolean DEFAULT false,
	`stripePaymentIntentId` varchar(255),
	`stripeCheckoutSessionId` varchar(255),
	`amountPaid` int DEFAULT 0,
	`soulprintSessionId` varchar(255),
	`soulprintStatus` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`soulprintData` json,
	`combinedReportData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `soulprint_orders_id` PRIMARY KEY(`id`)
);
